---
- name: Install NeoVim (& dependencies)
  become: "yes"
  apt:
    pkg:
      - fzf
      - git
      - neovim
      - nodejs
      - npm
      - silversearcher-ag
      - ruby
      - ruby-dev
    state: present

- name: Create NeoVim directories
  file:
    path: "{{ vim_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - autoload
    - plugged

- name: Copy init.vim config
  copy:
    src: init.vim
    dest: "{{ vim_dir }}/init.vim"
    mode: "0644"
  register: vim_config

- name: Install Plug.vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_dir }}/autoload/plug.vim"
    mode: "0755"
  register: vim_config

- name: Install plugins  # noqa 305 503
  shell: nvim --headless +PlugInstall +qall
  when: vim_config.changed

- name: Install SolarGraph gem for Ruby CoC
  community.general.gem:
    name: solargraph
    state: present

- name: Install NeoVim gem for CoC
  community.general.gem:
    name: neovim
    state: present

- name: Copy CoC settings
  copy:
    src: coc-settings.json
    dest: "{{ vim_dir }}/coc-settings.json"
    mode: "0755"
